---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-java-env
  namespace: games
  labels:
    app.kubernetes.io/controller: minecraft
    app.kubernetes.io/instance: minecraft-java
    app.kubernetes.io/name: minecraft-java
data:
  DIFFICULTY: "2"
  ENABLE_COMMAND_BLOCK: "true"
  ENABLE_WHITELIST: "true"
  EULA: "TRUE"
  EXISTING_OPS_FILE: "SKIP"
  LEVEL: "Valley-of-Vanilla"
  MEMORY: "4096M"
  MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
  MODRINTH_PROJECTS: "@/data/modrinth-projects.txt"
  MOTD: "Powered by BinaryNexus"
  ONLINE_MODE: "true"
  OVERRIDE_WHITELIST: "true"
  PAUSE_WHEN_EMPTY_SECONDS: "600"
  TYPE: "FABRIC"
  TZ: "America/New_York"
  VERSION: "LATEST"
