master:
  replicaCount: 1
worker:
  config:
    core:
      labelSources: ["pci", "system", "usb"]
  tolerations:
    - key: sku
      operator: Equal
      value: gpu
      effect: NoSchedule
prometheus:
  enable: true
