---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/resources.teleport.dev/teleportrolev8_v1.json
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV8
metadata:
  name: desktop-user
  namespace: teleport
spec:
  allow:
    windows_desktop_logins: ['{{internal.windows_logins}}', 'joshua']
    windows_desktop_labels:
      "*": "*"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/resources.teleport.dev/teleportrolev8_v1.json
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV8
metadata:
  name: cluster-admin
  namespace: teleport
spec:
  allow:
    logins: ['{{internal.logins}}', 'root', 'joshua']
    node_labels:
      "*": "*"
    kubernetes_groups: ["system:masters"]
    kubernetes_labels:
      "*": "*"
    app_labels:
      "*": "*"
    windows_desktop_labels:
      "*": "*"
    windows_desktop_logins: ['{{internal.windows_logins}}', 'joshua']
    rules:
      - resources: ["*"]
        verbs: ["*"]
