---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-shared
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: HomeOps-Public-IP
        metadataPolicy: None
      secretKey: HomeOpsPublicIP
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: minecraft-shared-secret
    template:
      data:
        HomeOpsPublicIP: "{{ .HomeOpsPublicIP }}"
      engineVersion: v2
      mergePolicy: Replace
