---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: ai
spec:
  storageClassName: miroir-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
