---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddns-updater
  namespace: network
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Cloudflare-Api-Token
        metadataPolicy: None
      secretKey: CF_API_TOKEN
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Cloudflare-Zone-Id
        metadataPolicy: None
      secretKey: CF_ZONE_ID
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: ddns-updater-secret
    template:
      data:
        config.json: |
          {
            "settings": [
              {
                "provider": "cloudflare",
                "zone_identifier": "{{ .CF_ZONE_ID }}",
                "domain": "unscfleet.com",
                "host": "mc-java",
                "token": "{{ .CF_API_TOKEN }}",
                "ip_version": "ipv4",
                "ttl": 1,
                "proxied": false
              }
            ]
          }
      engineVersion: v2
      mergePolicy: Replace
