---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb
spec:
  data:
    - remoteRef:
        key: CouchDB-User
      secretKey: COUCHDB_USER
    - remoteRef:
        key: CouchDB-Password
      secretKey: COUCHDB_PASSWORD
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: couchdb-secret
    template:
      data:
        COUCHDB_USER: "{{ .COUCHDB_USER }}"
        COUCHDB_PASSWORD: "{{ .COUCHDB_PASSWORD }}"
      engineVersion: v2
