---
alerting:
  pushover:
    application-token: "${PUSHOVER_APP_KEY}"
    user-key: "${PUSHOVER_USER_KEY}"
    default-alert:
      enabled: true
      description: "Healthcheck failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  path: /config/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/1706923
  link: https://github.com/binaryn3xus
  buttons:
    - name: Github
      link: https://github.com/binaryn3xus
    - name: Homelab
      link: https://github.com/binaryn3xus/HomeOps

web:
  port: 80
  header: Status
