apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/controller: sabnzbd
    app.kubernetes.io/service: sabnzbd
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/controller: sabnzbd
