apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
    spec:
      initContainers:
        - name: download-mcp-server
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -xe
              apk add --no-cache curl tar
              curl -L https://github.com/github/github-mcp-server/releases/download/v0.32.0/github-mcp-server_Linux_x86_64.tar.gz | tar -xz -C /mcp/bin github-mcp-server
              chmod +x /mcp/bin/github-mcp-server
          volumeMounts:
            - name: bin
              mountPath: /mcp/bin
      containers:
        - name: mcp-gateway
          image: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http
            - containerPort: 3000
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /app/mcpx.yaml
              subPath: mcpx.yaml
            - name: bin
              mountPath: /mcp/bin
      volumes:
        - name: config
          configMap:
            name: mcp-gateway-config
        - name: bin
          emptyDir: {}
