---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-secrets
spec:
  data:
    - remoteRef:
        key: Github-MCP-Token
      secretKey: GITHUB_PERSONAL_TOKEN
    - remoteRef:
        key: Work-GithubEnterprise-Token
      secretKey: GITHUB_ENTERPRISE_TOKEN
    - remoteRef:
        key: Work-GithubEnterprise-Url
      secretKey: GITHUB_ENTERPRISE_URL
    - remoteRef:
        key: Mcp-Gateway-Auth-Token
      secretKey: MCP_AUTH_TOKEN
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: mcp-secrets
    template:
      engineVersion: v2
