---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-gateway-external
  namespace: ai
  annotations:
    gatus.home-operations.com/endpoint: |-
      group: external
      conditions:
        - "[STATUS] == 405"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - mcp.unscfleet.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
          method: GET
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /mcp
      backendRefs:
        - group: ""
          kind: Service
          name: mcp-gateway-svc
          port: 8080
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
          headers:
            - name: X-Auth-Token
              type: Exact
              value: "${MCP_AUTH_TOKEN}"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /mcp
      backendRefs:
        - group: ""
          kind: Service
          name: mcp-gateway-svc
          port: 8080
          weight: 1
