---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
configMapGenerator:
  - name: mcp-gateway-config
    files:
      - mcp.json
      - app.yaml
generatorOptions:
  disableNameSuffixHash: false
