settings:
  config:
    url: http://tdarr.default.svc.cluster.local:8265
    verify_ssl: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 1m
    scrapeTimeout: 10s
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    memory: 256Mi
