---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: app
          image: ghcr.io/haveagitgat/tdarr:2.86.01@sha256:45742f00e51a58553844c8b13d97e7ae9b2ee9a056bd8e5993d9a8282a45a23f
          env:
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "568"
            - name: PGID
              value: "568"
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8265"
            - name: internalNode
              value: "true"
            - name: nodeID
              value: "internal-node"
          ports:
            - name: http
              containerPort: 8265
            - name: server
              containerPort: 8266
          startupProbe:
            httpGet:
              path: /
              port: 8265
            failureThreshold: 60
            periodSeconds: 10
          livenessProbe: &probe
            httpGet:
              path: /
              port: 8265
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe: *probe
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
              gpu.intel.com/i915: "1"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /app/server
            - name: media
              mountPath: /media
            - name: temp
              mountPath: /temp
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tdarr
        - name: media
          persistentVolumeClaim:
            claimName: synology-media
        - name: temp
          emptyDir: {}
