---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-openebs-pvc
  namespace: ai
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
