---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: bazarr-dst
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
