---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-cortana
  namespace: ai
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Discord-Cortana-Bot-Token
        metadataPolicy: None
      secretKey: discord_token
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Google-Gemini-API-HomeOps-Key
        metadataPolicy: None
      secretKey: gemini_api_key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Paperless-Api-Auth-Token
        metadataPolicy: None
      secretKey: paperless_token
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Github-Cortana-Token
        metadataPolicy: None
      secretKey: github_token
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Talos-Config
        metadataPolicy: None
      secretKey: talos_config
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Unifi-API-Key
        metadataPolicy: None
      secretKey: unifi_api_key
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: openclaw-cortana-secret
    template:
      data:
        DISCORD_BOT_TOKEN: "{{ .discord_token }}"
        GEMINI_API_KEY: "{{ .gemini_api_key }}"
        PPLS_HOSTNAME: "http://paperless.paperless.svc.cluster.local:8000"
        PPLS_TOKEN: "{{ .paperless_token }}"
        GH_TOKEN: "{{ .github_token }}"
        GITHUB_TOKEN: "{{ .github_token }}"
        TALOS_CONFIG: "{{ .talos_config }}"
        UNIFI_API_KEY: "{{ .unifi_api_key }}"
      engineVersion: v2
      mergePolicy: Replace
