apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: pikvm
  namespace: network
spec:
  endpoints:
    - ip:
        address: 10.0.30.5
        port: 443
  tls:
    insecureSkipVerify: true
