apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: audiobookshelf
      app.kubernetes.io/instance: audiobookshelf
      app.kubernetes.io/controller: audiobookshelf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audiobookshelf
        app.kubernetes.io/instance: audiobookshelf
        app.kubernetes.io/controller: audiobookshelf
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: app
          image: ghcr.io/advplyr/audiobookshelf:2.33.2
          env:
            - name: TZ
              value: America/New_York
            - name: AUDIOBOOKSHELF_UID
              value: "568"
            - name: AUDIOBOOKSHELF_GID
              value: "568"
            - name: CONFIG_PATH
              value: /config
            - name: METADATA_PATH
              value: /config/metadata
          ports:
            - name: http
              containerPort: 80
          livenessProbe: &probe
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probe
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 1500Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: tmpfs
              mountPath: /.npm
              subPath: .npm
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf
        - name: media
          persistentVolumeClaim:
            claimName: synology-media
        - name: tmpfs
          emptyDir: {}
