---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unscfleet-com
  namespace: network
spec:
  secretName: unscfleet-com-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: unscfleet.com
  dnsNames:
    - unscfleet.com
    - "*.unscfleet.com"
