---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Cloudflare-Api-Token
        metadataPolicy: None
      secretKey: CF_API_TOKEN
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Cloudflare-Zone-Id
        metadataPolicy: None
      secretKey: CF_ZONE_ID
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: cloudflare-dns-secret
    template:
      data:
        CF_API_TOKEN: "{{ .CF_API_TOKEN }}"
        CF_ZONE_ID: "{{ .CF_ZONE_ID }}"
      engineVersion: v2
      mergePolicy: Replace
