---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: ollama
            path: kubernetes/apps/ai/ollama/app
          - app: openclaw-operator
            path: kubernetes/apps/ai/openclaw-operator/operator
          - app: openclaw-instances
            path: kubernetes/apps/ai/openclaw-operator/instances
          - app: comfyui
            path: kubernetes/apps/ai/comfyui/app
            wave: "1"
          - app: mcp-gateway
            path: kubernetes/apps/ai/mcp-gateway/app
            exclude: "mcp.json"
            wave: "1"
          - app: open-webui
            path: kubernetes/apps/ai/open-webui/app
            wave: "1"
          - app: searxng
            path: kubernetes/apps/ai/searxng/app
            wave: "1"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
        directory:
          exclude: '{{ .exclude | default "namespace.yaml" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: ai
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
