---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: comfyui
            path: kubernetes/apps/ai/comfyui/app
          - app: cortana
            path: kubernetes/apps/ai/openclaw-operator/instances/cortana
          - app: mcp-gateway
            path: kubernetes/apps/ai/mcp-gateway/app
          - app: ollama
            path: kubernetes/apps/ai/ollama/app
          - app: open-webui
            path: kubernetes/apps/ai/open-webui/app
          - app: openclaw-operator
            path: kubernetes/apps/ai/openclaw-operator/operator
          - app: searxng
            path: kubernetes/apps/ai/searxng/app
  template:
    metadata:
      name: "{{.app}}"
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ai
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
