---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: database-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: cloudnative-pg-operator
            path: kubernetes/apps/database/cloudnative-pg/operator
            wave: "-3"
          - app: cloudnative-pg-cluster
            path: kubernetes/apps/database/cloudnative-pg/cluster
            wave: "-1"
          - app: cloudnative-pg-plugin-barman-cloud
            path: kubernetes/apps/database/cloudnative-pg/plugin-barman-cloud
            wave: "-1"
          - app: mssql-2025
            path: kubernetes/apps/database/mssql-2025/app
            wave: "-1"
          - app: cloudbeaver
            path: kubernetes/apps/database/cloudbeaver/app
            wave: "1"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
        directory:
          exclude: "namespace.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: database
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
