---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: audiobookshelf
          - app: bazarr
          - app: n8n
  template:
    metadata:
      name: "{{.app}}"
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: kubernetes/apps/default/{{.app}}/app
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
