---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: mosquitto
            path: kubernetes/apps/default/mosquitto/app
            wave: "-1"
          - app: audiobookshelf
            path: kubernetes/apps/default/audiobookshelf/app
          - app: bazarr
            path: kubernetes/apps/default/bazarr/app
          - app: esphome
            path: kubernetes/apps/default/esphome/app
          - app: home-assistant
            path: kubernetes/apps/default/home-assistant/app
          - app: it-tools
            path: kubernetes/apps/default/it-tools/app
          - app: jellyfin
            path: kubernetes/apps/default/jellyfin/app
          - app: maintainerr
            path: kubernetes/apps/default/maintainerr/app
            wave: "1"
          - app: n8n
            path: kubernetes/apps/default/n8n/app
          - app: overseerr
            path: kubernetes/apps/default/overseerr/app
            wave: "1"
          - app: plex
            path: kubernetes/apps/default/plex/app
          - app: prowlarr
            path: kubernetes/apps/default/prowlarr/app
          - app: radarr
            path: kubernetes/apps/default/radarr/app
            wave: "1"
          - app: sabnzbd
            path: kubernetes/apps/default/sabnzbd/app
          - app: sonarr
            path: kubernetes/apps/default/sonarr/app
            wave: "1"
          - app: tautulli
            path: kubernetes/apps/default/tautulli/app
            wave: "1"
          - app: tdarr
            path: kubernetes/apps/default/tdarr/app
          - app: vert
            path: kubernetes/apps/default/vert/app
          - app: watchstate
            path: kubernetes/apps/default/watchstate/app
            wave: "1"
          - app: zigbee
            path: kubernetes/apps/default/zigbee/app
          - app: zwave
            path: kubernetes/apps/default/zwave/app
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
        directory:
          exclude: "namespace.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
