---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
# Helm-based External Secrets Apps
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-helm-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: external-secrets
            path: kubernetes/apps/external-secrets/operator
            chart: external-secrets
            repo: oci://ghcr.io/external-secrets/charts/external-secrets
            version: 2.2.0
            wave: "-4"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      sources:
        - repoURL: https://github.com/binaryn3xus/HomeOps
          targetRevision: main
          ref: values
        - repoURL: https://github.com/binaryn3xus/HomeOps
          targetRevision: main
          path: "{{.path}}"
        - repoURL: "{{.repo}}"
          chart: "{{.chart}}"
          targetRevision: "{{.version}}"
          helm:
            releaseName: "{{.app}}"
            valueFiles:
              - $values/{{.path}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
---
# Plain Manifest External Secrets Apps
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-plain-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: volsync-secret
            path: kubernetes/apps/external-secrets/volsync-secret
            wave: "-3"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
