---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: envoy-gateway
            path: kubernetes/apps/network/envoy-gateway/app
            wave: "-1"
          - app: certificates-import
            path: kubernetes/apps/network/certificates/import
            wave: "-1"
          - app: certificates-export
            path: kubernetes/apps/network/certificates/export
            wave: "0"
          - app: cloudflare-dns
            path: kubernetes/apps/network/cloudflare-dns/app
            wave: "0"
          - app: cloudflare-tunnel
            path: kubernetes/apps/network/cloudflare-tunnel/app
            wave: "0"
          - app: unifi-dns
            path: kubernetes/apps/network/unifi-dns/app
            wave: "0"
          - app: echo
            path: kubernetes/apps/network/echo/app
            wave: "1"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{default "0" .wave}}"
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: network
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
