---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs-system
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
# Helm-based OpenEBS Apps
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openebs-system-helm-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: openebs
            path: kubernetes/apps/openebs-system
            chart: openebs
            repo: oci://ghcr.io/home-operations/charts-mirror/openebs
            version: 4.4.0
            wave: "-5"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      sources:
        - repoURL: https://github.com/binaryn3xus/HomeOps
          targetRevision: main
          ref: values
        - repoURL: https://github.com/binaryn3xus/HomeOps
          targetRevision: main
          path: "{{.path}}"
        - repoURL: "{{.repo}}"
          chart: "{{.chart}}"
          targetRevision: "{{.version}}"
          helm:
            releaseName: "{{.app}}"
            valueFiles:
              - $values/{{.path}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: openebs-system
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
