---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openebs-system-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: openebs
            path: kubernetes/apps/openebs-system/openebs/app
  template:
    metadata:
      name: "{{.app}}"
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: openebs-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
