---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: paperless-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: paperless
            path: kubernetes/apps/paperless/paperless-ngx/app
          - app: paperless-gotenberg
            path: kubernetes/apps/paperless/gotenberg/app
          - app: paperless-postgres
            path: kubernetes/apps/paperless/postgres/app
          - app: paperless-tika
            path: kubernetes/apps/paperless/tika/app
          - app: paperless-valkey
            path: kubernetes/apps/paperless/valkey/app
          - app: paperless-infra
            path: kubernetes/apps/paperless/paperless-infra/app
  template:
    metadata:
      name: "{{.app}}"
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: paperless
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
