---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: paperless-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: paperless-resources
            path: kubernetes/apps/paperless/resources
            wave: "-2"
          - app: paperless-postgres
            path: kubernetes/apps/paperless/postgres
            wave: "-1"
          - app: valkey
            path: kubernetes/apps/paperless/valkey
            wave: "-1"
          - app: gotenberg
            path: kubernetes/apps/paperless/gotenberg
          - app: tika
            path: kubernetes/apps/paperless/tika
          - app: paperless
            path: kubernetes/apps/paperless/paperless
            wave: "1"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: paperless
      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
