---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: rook-ceph-operator
            path: kubernetes/apps/rook-ceph/rook-ceph/app
            wave: "-5"
          - app: rook-ceph-cluster
            path: kubernetes/apps/rook-ceph/rook-ceph/cluster
            wave: "-4"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
        directory:
          exclude: '{{ .exclude | default "namespace.yaml" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: rook-ceph
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
