---
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-upgrade-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: etcd-defrag
            path: kubernetes/apps/system-upgrade/etcd-defrag/app
          - app: tuppr
            path: kubernetes/apps/system-upgrade/tuppr/app
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
        directory:
          exclude: "namespace.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: system-upgrade
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
