---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-cluster
  namespace: argocd
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/binaryn3xus/HomeOps/
      targetRevision: main
      ref: values
    - chart: teleport-cluster
      repoURL: https://charts.releases.teleport.dev
      targetRevision: 18.7.3
      helm:
        releaseName: teleport-cluster
        valueFiles:
          - $values/kubernetes/apps/teleport/cluster/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
