---
apiVersion: v1
kind: Namespace
metadata:
  name: volsync-system
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: volsync-system-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: volsync-operator
            path: kubernetes/apps/volsync-system/volsync/app
            wave: "-3"
          - app: volsync-snapshot-controller
            path: kubernetes/apps/volsync-system/snapshot-controller/app
            wave: "-3"
          - app: volsync-kopia
            path: kubernetes/apps/volsync-system/kopia/app
            wave: "-2"
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps/
        targetRevision: main
        path: "{{.path}}"
        directory:
          exclude: '{{ .exclude | default "namespace.yaml" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: volsync-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
