services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
      - "8212:8212/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVER_NAME=UNSC-Palworld
      - SERVER_PASSWORD=azkv://K8sHomeOpsKeyVault/Palworld-Server-Password
      - ADMIN_PASSWORD=azkv://K8sHomeOpsKeyVault/Palworld-Admin-Password
      - PLAYERS=16
      - MULTITHREADING=true
      - UPDATE_ON_BOOT=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - QUERY_PORT=27015
      - BACKUP_ENABLED=true
      - DELETE_OLD_BACKUPS=false
      - OLD_BACKUP_DAYS=30
      - BACKUP_CRON_EXPRESSION=0 */4 * * *
      - AUTO_UPDATE_ENABLED=true
      - AUTO_UPDATE_CRON_EXPRESSION=0 4 * * *
      - AUTO_UPDATE_WARN_MINUTES=30
      - AUTO_REBOOT_ENABLED=false
      - AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE=false
      - AUTO_REBOOT_WARN_MINUTES=5
      - AUTO_REBOOT_CRON_EXPRESSION=0 0 * * *
      - AUTO_PAUSE_ENABLED=false
      - AUTO_PAUSE_TIMEOUT_EST=180
      - AUTO_PAUSE_LOG=true
      - AUTO_PAUSE_DEBUG=false
      - AUTO_PAUSE_KNOCKD_IF=auto
      - ENABLE_PLAYER_LOGGING=true
      - PLAYER_LOGGING_POLL_PERIOD=5
      - LOG_FILTER_ENABLED=true
      - LOG_LEVEL=INFO
      - LOG_FORMAT_TYPE=default

      - DISCORD_WEBHOOK_URL=azkv://K8sHomeOpsKeyVault/Palworld-Discord-Webhook-Url
      - DISCORD_SUPPRESS_NOTIFICATIONS=true
      - DISCORD_CONNECT_TIMEOUT=30
      - DISCORD_MAX_TIMEOUT=30
      - DISCORD_PRE_UPDATE_BOOT_MESSAGE=Server is updating...
      - DISCORD_PRE_UPDATE_BOOT_MESSAGE_ENABLED=false
      #- DISCORD_PRE_UPDATE_BOOT_MESSAGE_URL=
      - DISCORD_POST_UPDATE_BOOT_MESSAGE=Server update complete!
      - DISCORD_POST_UPDATE_BOOT_MESSAGE_ENABLED=false
      #- DISCORD_POST_UPDATE_BOOT_MESSAGE_URL=
      - DISCORD_PRE_START_MESSAGE=Server has been started!
      - DISCORD_PRE_START_MESSAGE_ENABLED=false
      #- DISCORD_PRE_START_MESSAGE_URL=
      - DISCORD_PRE_SHUTDOWN_MESSAGE=Server is shutting down...
      - DISCORD_PRE_SHUTDOWN_MESSAGE_ENABLED=false
      #- DISCORD_PRE_SHUTDOWN_MESSAGE_URL=
      - DISCORD_POST_SHUTDOWN_MESSAGE=Server is stopped!
      - DISCORD_POST_SHUTDOWN_MESSAGE_ENABLED=false
      #- DISCORD_POST_SHUTDOWN_MESSAGE_URL=
      - DISCORD_PLAYER_JOIN_MESSAGE=player_name has dropped onto the server Palworld!
      - DISCORD_PLAYER_JOIN_MESSAGE_ENABLED=true
      #- DISCORD_PLAYER_JOIN_MESSAGE_URL=
      - DISCORD_PLAYER_LEAVE_MESSAGE=player_name has disconnected from the server.
      - DISCORD_PLAYER_LEAVE_MESSAGE_ENABLED=true
      #- DISCORD_PLAYER_LEAVE_MESSAGE_URL=
      - DISCORD_PRE_BACKUP_MESSAGE=Creating backup...
      - DISCORD_PRE_BACKUP_MESSAGE_ENABLED=false
      #- DISCORD_PRE_BACKUP_MESSAGE_URL=
      - DISCORD_POST_BACKUP_MESSAGE=Backup created at file_path
      - DISCORD_POST_BACKUP_MESSAGE_ENABLED=true
      #- DISCORD_POST_BACKUP_MESSAGE_URL=
      - DISCORD_PRE_BACKUP_DELETE_MESSAGE=Removing backups older than old_backup_days days
      - DISCORD_PRE_BACKUP_DELETE_MESSAGE_ENABLED=true
      #- DISCORD_PRE_BACKUP_DELETE_MESSAGE_URL=
      - DISCORD_POST_BACKUP_DELETE_MESSAGE=Removed backups older than old_backup_days days
      - DISCORD_POST_BACKUP_DELETE_MESSAGE_ENABLED=true
      #- DISCORD_POST_BACKUP_DELETE_MESSAGE_URL=
      - DISCORD_ERR_BACKUP_DELETE_MESSAGE=Unable to delete old backups, OLD_BACKUP_DAYS is not an integer. OLD_BACKUP_DAYS=old_backup_days
      - DISCORD_ERR_BACKUP_DELETE_MESSAGE_ENABLED=true
      #- DISCORD_ERR_BACKUP_DELETE_MESSAGE_URL=

      - DIFFICULTY=None
      - RANDOMIZER_TYPE=
      - RANDOMIZER_SEED=none
      - DAYTIME_SPEEDRATE=1.000000
      - NIGHTTIME_SPEEDRATE=1.000000
      - EXP_RATE=5.000000
      - PAL_CAPTURE_RATE=1.000000
      - PAL_SPAWN_NUM_RATE=1.000000
      - PAL_DAMAGE_RATE_ATTACK=1.000000
      - PAL_DAMAGE_RATE_DEFENSE=1.000000
      - PLAYER_DAMAGE_RATE_ATTACK=1.000000
      - PLAYER_DAMAGE_RATE_DEFENSE=1.000000
      - PLAYER_STOMACH_DECREASE_RATE=1.000000
      - PLAYER_STAMINA_DECREASE_RATE=1.000000
      - PLAYER_AUTO_HP_REGEN_RATE=1.000000
      - PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP=1.000000
      - PAL_STOMACH_DECREASE_RATE=0.500000
      - PAL_STAMINA_DECREASE_RATE=0.500000
      - PAL_AUTO_HP_REGEN_RATE=1.000000
      - PAL_AUTO_HP_REGEN_RATE_IN_SLEEP=2.000000
      - BUILD_OBJECT_HP_RATE=1.000000
      - BUILD_OBJECT_DAMAGE_RATE=0.000000
      - BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.000000
      - COLLECTION_DROP_RATE=1.000000
      - COLLECTION_OBJECT_HP_RATE=1.000000
      - COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1.000000
      - ENEMY_DROP_ITEM_RATE=2.000000
      - DEATH_PENALTY=Item
      - ENABLE_PLAYER_TO_PLAYER_DAMAGE=False
      - ENABLE_FRIENDLY_FIRE=False
      - ENABLE_INVADER_ENEMY=True
      - ACTIVE_UNKO=False
      - ENABLE_AIM_ASSIST_PAD=True
      - ENABLE_AIM_ASSIST_KEYBOARD=False
      - DROP_ITEM_MAX_NUM=3000
      - DROP_ITEM_MAX_NUM_UNKO=100
      - BASE_CAMP_MAX_NUM=128
      - BASE_CAMP_WORKER_MAX_NUM=25
      - DROP_ITEM_ALIVE_MAX_HOURS=1.000000
      - AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=False
      - AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.00000
      - GUILD_PLAYER_MAX_NUM=20
      - BASE_CAMP_MAX_NUM_IN_GUILD=5
      - PAL_EGG_DEFAULT_HATCHING_TIME=0.000000
      - WORK_SPEED_RATE=1.000000
      - AUTO_SAVE_SPAN=30.000000
      - IS_MULTIPLAY=False
      - IS_PVP=False
      - HARDCORE=False
      - CHARACTER_RECREATE_IN_HARDCORE=False
      - PAL_LOST=False
      - CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=False
      - ENABLE_NON_LOGIN_PENALTY=True
      - ENABLE_FAST_TRAVEL=True
      - IS_START_LOCATION_SELECT_BY_MAP=False
      - EXIST_PLAYER_AFTER_LOGOUT=False
      - ENABLE_DEFENSE_OTHER_GUILD_PLAYER=False
      - INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX=False
      - BUILD_AREA_LIMIT=False
      - ITEM_WEIGHT_RATE=0.000000
      - COOP_PLAYER_MAX_NUM=4
      - REGION=
      - USEAUTH=True
      - BAN_LIST_URL=https://b.palworldgame.com/api/banlist.txt
      - REST_API_ENABLED=True
      - REST_API_PORT=8212
      - ENABLE_GAMEDATA_API=false
      - SHOW_PLAYER_LIST=False
      - CHAT_POST_LIMIT_PER_MINUTE=30
      - ENABLE_PREDATOR_BOSS_PAL=True
      - MAX_BUILDING_LIMIT_NUM=0
      - SERVER_REPLICATE_PAWN_CULL_DISTANCE=15000.000000
      - SERVER_REPLICATE_PAWN_CULL_DISTANCE_IN_BASE_CAMP=5000.000000
      - CROSSPLAY_PLATFORMS=(Steam,Xbox,PS5,Mac)
      - USE_BACKUP_SAVE_DATA=True
      - USE_DEPOT_DOWNLOADER=False
      - INSTALL_BETA_INSIDER=False
      - ALLOW_GLOBAL_PALBOX_EXPORT=True
      - ALLOW_GLOBAL_PALBOX_IMPORT=True
      - EQUIPMENT_DURABILITY_DAMAGE_RATE=0.000000
      - ITEM_CONTAINER_FORCE_MARK_DIRTY_INTERVAL=1.000000
      - ITEM_CORRUPTION_MULTIPLIER=0.000000
      - PHYSICS_ACTIVE_DROP_ITEM_MAX_NUM=-1
      - ALLOW_CLIENT_MOD=True
      - PLAYER_DATA_PAL_STORAGE_UPDATE_CHECK_TICK_INTERVAL=1.000000
      - IS_SHOW_JOIN_LEFT_MESSAGE=True
      - MONSTER_FARM_ACTION_SPEED_RATE=1.000000
      - DENY_TECHNOLOGY_LIST=
      - GUILD_REJOIN_COOLDOWN_MINUTES=0
      - AUTO_TRANSFER_MASTER_CHECK_INTERVAL_SECONDS=3600.000000
      - AUTO_TRANSFER_MASTER_THRESHOLD_DAYS=14
      - MAX_GUILDS_PER_FRAME=10
      - BLOCK_RESPAWN_TIME=3.000000
      - RESPAWN_PENALTY_DURATION_THRESHOLD=0.000000
      - RESPAWN_PENALTY_TIME_SCALE=2.000000
      - DISPLAY_PVP_ITEM_NUM_ON_WORLD_MAP_BASE_CAMP=False
      - DISPLAY_PVP_ITEM_NUM_ON_WORLD_MAP_PLAYER=False
      - ADDITIONAL_DROP_ITEM_WHEN_PLAYER_KILLING_IN_PVP_MODE=PlayerDropItem
      - ADDITIONAL_DROP_ITEM_NUM_WHEN_PLAYER_KILLING_IN_PVP_MODE=1
      - ADDITIONAL_DROP_ITEM_WHEN_PLAYER_KILLING_IN_PVP_MODE_ENABLED=False
      - ENABLE_VOICE_CHAT=False
      - VOICE_CHAT_MAX_VOLUME_DISTANCE=3000.000000
      - VOICE_CHAT_ZERO_VOLUME_DISTANCE=15000.000000
      - ALLOW_ENHANCE_STAT_HEALTH=True
      - ALLOW_ENHANCE_STAT_ATTACK=True
      - ALLOW_ENHANCE_STAT_STAMINA=True
      - ALLOW_ENHANCE_STAT_WEIGHT=True
      - ALLOW_ENHANCE_STAT_WORK_SPEED=True
      - ENABLE_BUILDING_PLAYER_UID_DISPLAY=False
      - BUILDING_NAME_DISPLAY_CACHE_TTL_SECONDS=60
    volumes:
      - /mnt/fastdata/palworld-data:/palworld
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 8G
  palworld-server-dashboard:
    image: ghcr.io/rnz01/palworld-server-dashboard:latest
    container_name: palworld-server-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=America/New_York
      - PANEL_INITIAL_ADMIN_PASSWORD=azkv://K8sHomeOpsKeyVault/Palworld-Dashboard-Admin-Password
      - PALWORLD_ADMIN_PASSWORD=azkv://K8sHomeOpsKeyVault/Palworld-Admin-Password
      - PALWORLD_REST_URL=http://palworld-server:8212
      - PALWORLD_DOCKER_CONTAINER=palworld-server
      - PUBLIC_VIEW_ENABLED=true
    depends_on:
      - palworld
