---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: n8n-dst
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
