apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: default
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/controller: mosquitto
data:
  mosquitto.conf: |
    allow_anonymous true
    autosave_interval 60
    connection_messages false
    listener 1883
    per_listener_settings false
    persistence true
    persistence_location /config
