---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/configmap_v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: satisfactory-env
data:
  MAXPLAYERS: "8"
  AUTOSAVENUM: "5"
  MAXOBJECTS: "2162688"
  MAXTICKRATE: "30"
  SERVERSTREAMING: "true"
  TIMEOUT: "30"
  DISABLESEASONALEVENTS: "false"
  STEAMBETA: "false"
  SKIPUPDATE: "false"
  VMOVERRIDE: "false"
  DEBUG: "false"
  SERVERGAMEPORT: "7777"
  SERVERMESSAGINGPORT: "8888"
