apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ai
  annotations:
    lbipam.cilium.io/ips: "10.0.30.44"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      protocol: TCP
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/controller: ollama
