apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-2025-config
  namespace: database
data:
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Developer"
  MSSQL_AGENT_ENABLED: "true"
  MSSQL_DATA_DIR: "/var/opt/mssql/data"
  MSSQL_LOG_DIR: "/var/opt/mssql/log"
  MSSQL_BACKUP_DIR: "/var/opt/mssql/backup"
  TZ: "America/New_York"
