---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: mssql-2025
  app.kubernetes.io/instance: mssql-2025
  app.kubernetes.io/controller: main
resources:
  - ./configmap.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./externalsecret.yaml
