apiVersion: v1
kind: Service
metadata:
  name: mssql-2025
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mssql2025.unscfleet.com
    lbipam.cilium.io/ips: "10.0.30.41"
spec:
  type: LoadBalancer
  ports:
    - name: mssqlport
      port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    app.kubernetes.io/name: mssql-2025
    app.kubernetes.io/instance: mssql-2025
    app.kubernetes.io/controller: main
