---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns
  namespace: network
spec:
  data:
    - remoteRef:
        key: Cloudflare-Api-Token
      secretKey: CLOUDFLARE_API_TOKEN
    - remoteRef:
        key: Cloudflare-Zone-Id
      secretKey: CLOUDFLARE_ZONE_ID
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: cloudflare-ddns-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
        CLOUDFLARE_ZONE_ID: "{{ .CLOUDFLARE_ZONE_ID }}"
