apiVersion: v1
kind: Service
metadata:
  name: kopia
  namespace: volsync-system
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: kopia
    app.kubernetes.io/instance: kopia
    app.kubernetes.io/controller: kopia
