---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
