---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: teleport
  namespace: teleport
spec:
  sourcePVC: teleport
  trigger:
    schedule: "0 4 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: teleport-volsync-secret
    cacheCapacity: 2Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: teleport-dst
  namespace: teleport
spec:
  trigger:
    manual: restore
  restic:
    repository: teleport-volsync-secret
    copyMethod: Snapshot
    cacheCapacity: 2Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    previousPVC: teleport
