---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tika
  namespace: paperless
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      tika:
        containers:
          app:
            image:
              repository: apache/tika
              tag: 3.3.0.0
            ports:
              - containerPort: 9998
                name: http
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1024Mi
    service:
      app:
        controller: tika
        ports:
          http:
            port: 9998
