apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex
  namespace: default
  annotations:
    gatus.home-operations.com/endpoint: |-
      conditions: ["[STATUS] == 401"]
      group: external
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - plex.unscfleet.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /library/streams
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            remove: ["Range"]
      backendRefs:
        - group: ""
          kind: Service
          name: plex
          port: 32400
          weight: 1
    - backendRefs:
        - group: ""
          kind: Service
          name: plex
          port: 32400
          weight: 1
