---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: zwave
  app.kubernetes.io/instance: zwave
  app.kubernetes.io/controller: zwave
resources:
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./replicationdestination.yaml
  - ./replicationsource.yaml
