---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: detect-non-flux-managed-resources
  annotations:
    policies.kyverno.io/title: Detect Non-Flux Managed Resources
    policies.kyverno.io/category: GitOps
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy audits for resources that are not managed by Flux. 
      It checks for the absence of standard Flux labels like 'kustomize.toolkit.fluxcd.io/name' 
      and 'helm.toolkit.fluxcd.io/name'.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: check-flux-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - Service
                - Ingress
                - ConfigMap
                - Secret
                - CustomResourceDefinition
      exclude:
        any:
          - resources:
              names:
                - kube-root-ca.crt
          - resources:
              selector:
                matchExpressions:
                  - key: "app.kubernetes.io/managed-by"
                    operator: Exists
      validate:
        message: "Resource is not managed by Flux (missing Flux labels)."
        anyPattern:
          - metadata:
              labels:
                "kustomize.toolkit.fluxcd.io/name": "*"
          - metadata:
              labels:
                "helm.toolkit.fluxcd.io/name": "*"
