---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - values.yaml
configMapGenerator:
  - name: prometheus-operator-crds-status
    literals:
      - status=migrated-to-argo
