---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
  namespace: ai
spec:
  data:
    - remoteRef:
        key: HomeOps-LiteLLM-Master-Key
      secretKey: master_key
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: litellm-secret
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .master_key }}"
      engineVersion: v2
