---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db
  namespace: ai
spec:
  data:
    - remoteRef:
        key: HomeOps-LiteLLM-Postgres-Password
      secretKey: postgres_password
    - remoteRef:
        key: Postgres-Backup-Access-Key-Id
      secretKey: backup_access_key_id
    - remoteRef:
        key: Postgres-Backup-Access-Secret
      secretKey: backup_access_secret
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: litellm-db-secret
    template:
      data:
        username: litellm
        password: "{{ .postgres_password }}"
        DATABASE_URL: "postgresql://litellm:{{ .postgres_password }}@litellm-db-rw.ai.svc.cluster.local:5432/litellm"
        backupAccessKeyId: "{{ .backup_access_key_id }}"
        backupAccessSecret: "{{ .backup_access_secret }}"
      engineVersion: v2
