apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee-config
  labels:
    app.kubernetes.io/name: zigbee
    app.kubernetes.io/instance: zigbee
    app.kubernetes.io/controller: zigbee
data:
  TZ: America/New_York
  ZIGBEE2MQTT_DATA: /config
  ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: "25"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
  ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER: "20"
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: "60"
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: "2000"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "80"
  ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://zigbee.unscfleet.com"
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: "60"
  ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto:1883
  ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
  ZIGBEE2MQTT_CONFIG_ONBOARDING: "false"
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: "115200"
  ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://10.0.30.8:7638
  ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack
