---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    namespaceOverride: database
    certificate:
      duration: 8760h
      renewBefore: 720h
    image:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud
      tag: v0.14.0@sha256:823a8893690980ba5830bbbb11196a35f695b0488db7d846abc33baebf32417c
    sidecarImage:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud-sidecar
      tag: v0.14.0@sha256:9880817c285c7afa4d195da2145064d21907405489ed6ec39abe59b1feb558a4
