---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    namespaceOverride: database
    certificate:
      duration: 8760h
      renewBefore: 720h
    image:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud
      tag: v0.15.0@sha256:563c680fe7fda3466ca2b1f55a1397ed2ddc9e760360107dd7724f1959c1a536
    sidecarImage:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud-sidecar
      tag: v0.15.0@sha256:06c78deca670525daa35fb1e5323159092785d11cf87b86217bdd5c679a41a84
