namespaceOverride: database
certificate:
  duration: 8760h
  renewBefore: 720h
image:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud
  tag: v0.12.0@sha256:0b9c428123313d93efbec26bdef85e91f2130a7bd8e382a767de12b3938f6271
sidecarImage:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud-sidecar
  tag: v0.11.0@sha256:8e45fedbfaae916d7dff1160ea22648c2d21e6184479d3eb75e9ff0f3b23428a
