---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudbeaver
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: CloudBeaver-Root-Password
        metadataPolicy: None
      secretKey: CLOUDBEAVER_ROOT_PASSWORD
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudbeaver-secret
    template:
      data:
        CLOUDBEAVER_ROOT_PASSWORD: "{{ .CLOUDBEAVER_ROOT_PASSWORD }}"
      engineVersion: v2
      mergePolicy: Replace
