---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: flux-secrets
    template:
      engineVersion: v2
      data:
        # GitHub Webhook Token
        token: "{{ .GITHUB_WEBHOOK_TOKEN }}"
        # SSH Private Key for GitRepository
        identity: "{{ .SSH_PRIVATE_KEY }}"
        known_hosts: |
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFBWxts2ALojcOMWuzltlxpSt4/+ZlM27FVBp6hD9SxrA3vXyJ7X29BqN2K9vD4=
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1WozAXY2rbJPu8RA5nXw8Gln2sdztInsqSWGUcy1i5ivDcVqhWW70KE6DNSK4S2EQixfIDisK5Glsln650P+3Y0vO5V2S4J73E84nO4V6AAnuM6C7Y4qUAAAAIbmlzdHAyNTYAAAAIbmlzdHAyNTYAAAABBBEmKSENjQEezOmxkZMy7opKgwFBWxts2ALojcOMWuzltlxpSt4/+ZlM27FVBp6hD9SxrA3vXyJ7X29BqN2K9vD4=
  data:
    - secretKey: GITHUB_WEBHOOK_TOKEN
      remoteRef:
        key: Flux-Github-Token
    - secretKey: SSH_PRIVATE_KEY
      remoteRef:
        key: Flux-SSH-Key
