---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: flux-secrets
    template:
      engineVersion: v2
      data:
        # GitHub Webhook Token
        token: "{{ .GITHUB_WEBHOOK_TOKEN }}"
        # SSH Private Key for GitRepository
        identity: "{{ .SSH_PRIVATE_KEY }}"
        known_hosts: "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFBWxts2ALojcOMWuzltlxpSt4/+ZlM27FVBp6hD9SxrA3vXyJ7X29BqN2K9vD4="
  data:
    - secretKey: GITHUB_WEBHOOK_TOKEN
      remoteRef:
        key: Flux-Github-Token
    - secretKey: SSH_PRIVATE_KEY
      remoteRef:
        key: Flux-SSH-Key
