---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-fleet-auth
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Github-UNSC-Fleet-Auth-Client-Id
        metadataPolicy: None
      secretKey: client_id
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Github-UNSC-Fleet-Auth-Client-Secret
        metadataPolicy: None
      secretKey: client_secret
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OpenWebUI-Secret-Key
        metadataPolicy: None
      secretKey: webui_secret_key
    - secretKey: google_gemini_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Google-Gemini-API-HomeOps-Key
        metadataPolicy: None
    - secretKey: azure_speech_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Azure-HomeOps-Speech-Key
        metadataPolicy: None
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-fleet-auth-secret
    template:
      data:
        GITHUB_CLIENT_ID: "{{ .client_id }}"
        GITHUB_CLIENT_SECRET: "{{ .client_secret }}"
        WEBUI_SECRET_KEY: "{{ .webui_secret_key }}"
        OPENAI_API_KEY: "{{ .google_gemini_key }}"
        AUDIO_STT_AZURE_API_KEY: "{{ .azure_speech_key }}"
        AUDIO_TTS_API_KEY: "{{ .azure_speech_key }}"
      engineVersion: v2
      mergePolicy: Replace
