---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-cortana
  namespace: ai
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: openclaw-cortana-dst
  resources:
    requests:
      storage: 10Gi
