---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee
  namespace: default
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Zigbee-Extended-Id
        metadataPolicy: None
      secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Zigbee-Pan-Id
        metadataPolicy: None
      secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Zigbee-Network-Key
        metadataPolicy: None
      secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: zigbee-secret
    template:
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID }}"
      engineVersion: v2
      mergePolicy: Replace
