---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-agent
spec:
  interval: 15m
  chart:
    spec:
      chart: teleport-kube-agent
      version: 18.11.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: teleport
  values:
    log:
      level: INFO
    roles: kube,app,discovery
    proxyAddr: teleport.unscfleet.com:443
    hostAliases:
      - ip: "10.0.30.42"
        hostnames:
          - "teleport.unscfleet.com"
    joinParams:
      method: kubernetes
      tokenName: agent-join-token
    kubeClusterName: HomeOpsCluster
    updater:
      # Make absolutely certain that the auto updater is never enabled
      enabled: false
    teleportConfig:
      discovery_service:
        enabled: true
        kubernetes:
          - types: ["app"]
            labels:
              "teleport.dev/discover": "true"
      windows_desktop_service:
        enabled: true
        static_hosts:
        - name: UNSC-PillarOfAutumn
          addr: 10.0.20.10
