log:
  level: DEBUG
roles: kube,app,discovery,node,windowsdesktop
proxyAddr: teleport.teleport.svc.cluster.local:443
joinParams:
  method: kubernetes
  tokenName: agent-join-token
kubeClusterName: HomeOpsCluster
updater:
  enabled: false
podMonitor:
  enabled: true
extraVolumes:
  - name: proxy-cert-ca
    secret:
      secretName: teleport-intermediary-ca-secret
extraVolumeMounts:
  - name: proxy-cert-ca
    mountPath: /etc/teleport-proxy-cert
    readOnly: true
extraEnv:
  - name: SSL_CERT_FILE
    value: /etc/teleport-proxy-cert/tls.crt
teleportConfig:
  discovery_service:
    enabled: true
    kubernetes:
      - types: ["app"]
        labels:
          "teleport.dev/discover": "true"
  windows_desktop_service:
    enabled: true
    static_hosts:
    - name: UNSC-PillarOfAutumn
      addr: 10.0.20.10
