---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      expr: |-
        !has(status.phase) || status.phase in ['Succeeded', 'Failed', 'Orphaned']
      kind: Snapshot
    - apiVersion: ceph.rook.io/v1
      expr: |-
        status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
  policy:
    rebootMode: powercycle
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.10
  hooks:
    pre:
      - name: hibernate-postgres
        image: alpine/k8s:1.37.0
        serviceAccountName: tuppr-upgrade-hooks
        backoffLimit: 1
        command:
          - /bin/sh
          - -c
          - |
            # Set Ceph noout to prevent backfilling during maintenance
            kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph osd set noout

            # Suspend Flux Kustomizations
            kubectl patch kustomization -n database cloudnative-pg-cluster -p '{"spec":{"suspend":true}}' --type=merge
            kubectl patch kustomization -n paperless paperless-postgres -p '{"spec":{"suspend":true}}' --type=merge
            kubectl patch kustomization -n media tracearr -p '{"spec":{"suspend":true}}' --type=merge

            # Hibernate CNPG Clusters (scale to 0)
            kubectl annotate cluster -n database home-ops cnpg.io/hibernation=on --overwrite
            kubectl annotate cluster -n paperless paperless-postgres cnpg.io/hibernation=on --overwrite
            kubectl annotate cluster -n media tracearr-db cnpg.io/hibernation=on --overwrite
    post:
      - name: resume-postgres
        image: alpine/k8s:1.37.0
        serviceAccountName: tuppr-upgrade-hooks
        backoffLimit: 1
        command:
          - /bin/sh
          - -c
          - |
            # Turn off hibernation on Postgres Clusters
            kubectl annotate cluster -n database home-ops cnpg.io/hibernation=off --overwrite
            kubectl annotate cluster -n paperless paperless-postgres cnpg.io/hibernation=off --overwrite
            kubectl annotate cluster -n media tracearr-db cnpg.io/hibernation=off --overwrite

            # Resume Flux Kustomizations
            kubectl patch kustomization -n database cloudnative-pg-cluster -p '{"spec":{"suspend":false}}' --type=merge
            kubectl patch kustomization -n paperless paperless-postgres -p '{"spec":{"suspend":false}}' --type=merge
            kubectl patch kustomization -n media tracearr -p '{"spec":{"suspend":false}}' --type=merge

            # Unset Ceph noout to resume normal replication behavior
            kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph osd unset noout
