---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hermes-operator
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/ai/hermes-operator/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: ai
  timeout: 5m
