---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: watchstate
  app.kubernetes.io/instance: watchstate
  app.kubernetes.io/controller: watchstate
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
