---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: headroom
  namespace: ai
spec:
  podMetricsEndpoints:
    - port: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: headroom
      app.kubernetes.io/instance: headroom
      app.kubernetes.io/controller: headroom
