---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: headroom
  namespace: ai
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8787
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: headroom
    app.kubernetes.io/instance: headroom
    app.kubernetes.io/controller: headroom
