---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: comfyui
  app.kubernetes.io/instance: comfyui
  app.kubernetes.io/controller: comfyui
resources:
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
