---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
labels:
  - pairs:
      app.kubernetes.io/name: ${APP}
      app.kubernetes.io/instance: ${APP}
      app.kubernetes.io/controller: ${APP}
    includeSelectors: true
