apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: observability
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gatus
      app.kubernetes.io/instance: gatus
      app.kubernetes.io/controller: gatus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gatus
        app.kubernetes.io/instance: gatus
        app.kubernetes.io/controller: gatus
    spec:
      serviceAccountName: gatus
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: gatus-sidecar
          image: ghcr.io/home-operations/gatus-sidecar:0.3.5@sha256:aad3780968860cc4c9e8c63ed21595b1c8574a34678a6adfebe8dcb4b36f8dd2
          args:
            - --auto-httproute
            - --enable-httproute
          env:
            - name: TZ
              value: America/New_York
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          restartPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: app
          image: ghcr.io/twin/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
          env:
            - name: GATUS_CONFIG_PATH
              value: /config
            - name: GATUS_WEB_PORT
              value: "80"
            - name: TZ
              value: America/New_York
          envFrom:
            - secretRef:
                name: gatus-secret
          ports:
            - name: http
              containerPort: 80
          livenessProbe: &probe
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probe
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - NET_RAW
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-file
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: config
              mountPath: /config
      volumes:
        - name: config-file
          configMap:
            name: gatus-configmap
        - name: config
          persistentVolumeClaim:
            claimName: gatus-config
