---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: gatus
  app.kubernetes.io/instance: gatus
  app.kubernetes.io/controller: gatus
resources:
  - ./rbac.yaml
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
  - ./httproute.yaml
  - ./externalsecret.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: gatus-configmap
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
