---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gatus
  namespace: observability
spec:
  paused: false
  sourcePVC: gatus-config
  trigger:
    schedule: "0 2-22/4 * * *"
  kopia:
    accessModes: ["ReadWriteOnce"]
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 5Gi
    cacheStorageClassName: openebs-hostpath
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    repository: gatus-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
