# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  postgresql:
    parameters:
      # Explicit defaults to match controller
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false

  # Explicit default
  resources: {}

  storage:
    size: 10Gi
    storageClass: ceph-block
    # Explicit default
    resizeInUseVolumes: true

  monitoring:
    enablePodMonitor: true
    # Explicit defaults
    disableDefaultQueries: false
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      # Explicit defaults
      encoding: UTF8
      localeCType: C
      localeCollate: C
      secret:
        name: paperless-secrets
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname

  # Other explicit defaults
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  postgresGID: 26
  postgresUID: 26
  probes:
    liveness:
      isolationCheck:
        connectionTimeout: 1000
        enabled: true
        requestTimeout: 1000
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  switchoverDelay: 3600
