---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafanadashboard.yaml
configMapGenerator:
  - name: tuppr-dashboard
    files:
      - tuppr-dashboard.json
    options:
      disableNameSuffixHash: true
