---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-secrets
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Github-MCP-Token
        metadataPolicy: None
      secretKey: GITHUB_PERSONAL_TOKEN
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Work-GithubEnterprise-Token
        metadataPolicy: None
      secretKey: GITHUB_ENTERPRISE_TOKEN
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Work-GithubEnterprise-Url
        metadataPolicy: None
      secretKey: GITHUB_ENTERPRISE_URL
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Mcp-Gateway-Auth-Token
        metadataPolicy: None
      secretKey: MCP_AUTH_TOKEN
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: mcp-secrets
    template:
      engineVersion: v2
      mergePolicy: Replace
