---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  data:
    - remoteRef:
        key: HomeAssistant-Prometheus-Long-Lived-Access-Token
      secretKey: HASS_PROMETHEUS_TOKEN
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: home-assistant-secret
    template:
      data:
        HASS_PROMETHEUS_TOKEN: "{{ .HASS_PROMETHEUS_TOKEN }}"
      engineVersion: v2
