---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: searxng
  app.kubernetes.io/name: searxng
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - ./resources/settings.yml
      - ./resources/limiter.toml
generatorOptions:
  disableNameSuffixHash: true
