apiVersion: v1
kind: Service
metadata:
  name: searxng-app
  namespace: ai
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/controller: searxng
---
apiVersion: v1
kind: Service
metadata:
  name: searxng-redis
  namespace: ai
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/controller: redis
