apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-updater
  namespace: network
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ddns-updater
      app.kubernetes.io/instance: ddns-updater
      app.kubernetes.io/controller: ddns-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ddns-updater
        app.kubernetes.io/instance: ddns-updater
        app.kubernetes.io/controller: ddns-updater
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: app
          image: ghcr.io/qdm12/ddns-updater:v2.9.0
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: data
              mountPath: /updater/data
            - name: config
              mountPath: /updater/data/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          secret:
            secretName: ddns-updater-secret
