---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./namespace.yaml
  # Shared PVCs
  - ./synology.yaml
  # Apps
  - ./help-docs/ks.yaml
  - ./it-tools/ks.yaml
  - ./minecraft-java/ks.yaml
  - ./palworld
  - ./satisfactory/ks.yaml
  - ./unsc-gaming/ks.yaml
  - ./worksphere/ks.yaml

