---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-kubernetes
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: synology-nfs
  volumeName: synology-kubernetes
  resources:
    requests:
      storage: 1Mi
