---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: home-ops
  sources:
    # Source 1: The Argo CD Installation itself (Seed)
    - repoURL: oci://ghcr.io/argoproj/argo-helm/argo-cd
      chart: argo-cd
      targetRevision: 9.4.17
      helm:
        valueFiles:
          - $values/kubernetes/apps/argocd/app/values.yaml
    # Source 2: Your Git Repo (for the values file)
    - repoURL: https://github.com/binaryn3xus/HomeOps/
      targetRevision: main
      ref: values
    # Source 3: The Control Room (Discovery Pattern)
    - repoURL: https://github.com/binaryn3xus/HomeOps/
      targetRevision: main
      path: kubernetes/apps/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
