---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-sso
  namespace: argocd
spec:
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: argocd-github-sso
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        CLIENT_ID: "{{ .client_id }}"
        CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Github-ArgoCD-App-Client-Id
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Github-ArgoCD-App-Client-Secret
        metadataPolicy: None
