---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home-ops
  namespace: argocd
spec:
  description: Project for HomeOps applications
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  sourceRepos:
    - https://github.com/binaryn3xus/HomeOps/
    - oci://ghcr.io/*
    - oci://quay.io/*
    - https://charts.fairwinds.com/stable
    - https://kubernetes-sigs.github.io/node-feature-discovery/charts
    - https://nvidia.github.io/k8s-device-plugin
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
