# Argo CD Configuration
fullnameOverride: argocd

## Global
global:
  domain: argocd.unscfleet.com

## API/UI Server
server:
  service:
    type: ClusterIP
  ingress:
    enabled: false
  config:
    url: https://argocd.unscfleet.com
    exec.enabled: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

## Dex
dex:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

## Redis
redis:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

## Controller
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

## Repo Server
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

## Configuration
configs:
  params:
    server.insecure: true

  repositories:
    home-ops:
      url: https://github.com/binaryn3xus/HomeOps/
      type: git
      name: HomeOps

  rbac:
    policy.default: role:readonly
    policy.csv: |
      # p = Policy (Defining the role permissions)
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, *, *, allow
      p, role:org-admin, projects, *, *, allow

      # g = Grant (Mapping your user to the role)
      g, binaryn3xus, role:org-admin

  cm:
    url: https://argocd.unscfleet.com

    # GitHub SSO via Dex
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github-sso:CLIENT_ID
            clientSecret: $argocd-github-sso:CLIENT_SECRET

    # Custom Health Checks
    resource.customHealth.lua.helm.toolkit.fluxcd.io_HelmRelease: |
      hs = {}
      if obj.status ~= nil and obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
          if condition.type == "Ready" and condition.status == "False" then
            hs.status = "Degraded"
            hs.message = condition.message
            return hs
          end
        end
      end
      hs.status = "Progressing"
      return hs
    resource.customHealth.lua.kustomize.toolkit.fluxcd.io_Kustomization: |
      hs = {}
      if obj.status ~= nil and obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
        end
      end
      hs.status = "Progressing"
      return hs
