---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: minecraft-bedrock
  app.kubernetes.io/instance: minecraft-bedrock
  app.kubernetes.io/controller: minecraft
resources:
  - ./configmap.yaml
  - ./dnsendpoint.yaml
  - ./gatus.yaml
  - ./deployment.yaml
  - ./service.yaml
configMapGenerator:
  - name: minecraft-bedrock-allowlist
    files:
      - allowlist.json=./resources/allowlist.json
  - name: minecraft-bedrock-permissions
    files:
      - permissions.json=./resources/permissions.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
