---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: minecraft-bedrock-dst
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
