apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: games
  annotations:
    lbipam.cilium.io/ips: "10.0.30.37"
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 19132
      targetPort: 19132
      protocol: UDP
  selector:
    app.kubernetes.io/name: minecraft-bedrock
    app.kubernetes.io/instance: minecraft-bedrock
    app.kubernetes.io/controller: minecraft
