apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
