---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: nas
  credentialProjection:
    enabled: true
  sources:
    - pvc:
        name: ${APP}
  copyMethod: Snapshot
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
  retention:
    keepDaily: 7
    keepHourly: 24
  verification:
    deep:
      schedule:
        cron: H 5 * * 0
        jitter: 1h
        timezone: America/New_York
    quick:
      schedule:
        cron: H 5 * * *
        jitter: 1h
        timezone: America/New_York

