---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: nas
  credentialProjection:
    enabled: true
  sources:
    - pvc:
        name: ${APP}
  copyMethod: Snapshot
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
  compression:
    compressor: zstd
  mover:
    cache:
      capacity: ${KOPIUR_CACHE_CAPACITY:=5Gi}
      mode: Persistent
      storageClassName: ${KOPIUR_CACHE_STORAGECLASS:=miroir-local}
    securityContext:
      runAsUser: ${KOPIUR_PUID:=1000}
      runAsGroup: ${KOPIUR_PGID:=1000}
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  verification:
    deep:
      schedule:
        cron: H 5 * * 0
        jitter: 1h
        timezone: America/New_York
    quick:
      schedule:
        cron: H 5 * * *
        jitter: 1h
        timezone: America/New_York

