apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unifi-dns
  namespace: network
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: unifi-dns
      app.kubernetes.io/name: external-dns
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
