---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: tracearr-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .jwt_secret }}"
        COOKIE_SECRET: "{{ .cookie_secret }}"
        DB_PASSWORD: "{{ .db_password }}"
        username: tracearr
        password: "{{ .db_password }}"
        DATABASE_URL: "postgresql://tracearr:{{ .db_password }}@tracearr-db-rw.media.svc.cluster.local:5432/tracearr"
        REDIS_URL: "redis://tracearr-redis:6379"
        backupAccessKeyId: "{{ .r2_access_key }}"
        backupAccessSecret: "{{ .r2_secret_key }}"
  data:
    - remoteRef:
        key: tracearr-jwt-secret
      secretKey: jwt_secret
    - remoteRef:
        key: tracearr-cookie-secret
      secretKey: cookie_secret
    - remoteRef:
        key: tracearr-db-password
      secretKey: db_password
    - remoteRef:
        key: r2-access-key
      secretKey: r2_access_key
    - remoteRef:
        key: r2-secret-key
      secretKey: r2_secret_key
