---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: tracearr
  app.kubernetes.io/instance: tracearr
resources:
  - ./externalsecret.yaml
  - ./db-cluster.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
