---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readmeabook
spec:
  data:
    - remoteRef:
        key: ReadMeABook-Jwt-Secret
      secretKey: readmeabook_jwt_secret
    - remoteRef:
        key: ReadMeABook-Jwt-Refresh-Secret
      secretKey: readmeabook_jwt_refresh_secret
    - remoteRef:
        key: ReadMeABook-Config-Encryption-Key
      secretKey: readmeabook_config_encryption_key
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: readmeabook-secret
    template:
      data:
        JWT_SECRET: "{{ .readmeabook_jwt_secret }}"
        JWT_REFRESH_SECRET: "{{ .readmeabook_jwt_refresh_secret }}"
        CONFIG_ENCRYPTION_KEY: "{{ .readmeabook_config_encryption_key }}"
      engineVersion: v2
