---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: readmeabook
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3030
      protocol: TCP

