apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - synology.yaml
  - postgres/ks.yaml
  - valkey/ks.yaml
  - tika/ks.yaml
  - gotenberg/ks.yaml
  - paperless-ngx/ks.yaml
  - paperless-ai/ks.yaml
