apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-subnet-router-pc
  namespace: network
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
