---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-subnet-router-pc
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        env:
          - name: TS_EXTRA_ARGS
            value: "--snat-subnet-routes=false --stateful-filtering=false"
