---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  TZ: "America/New_York"
  PUID: "1000"
  PGID: "100"
  PAPERLESS_PORT: "8000"
  PAPERLESS_URL: "https://paperless.unscfleet.com"
  PAPERLESS_REDIS: "redis://valkey.paperless.svc.cluster.local:6379"
  PAPERLESS_DBHOST: "paperless-postgres-rw.paperless.svc.cluster.local"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_ENDPOINT: "http://tika.paperless.svc.cluster.local:9998"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg.paperless.svc.cluster.local:3000"
  PAPERLESS_GOTENBERG_ENDPOINT: "http://gotenberg.paperless.svc.cluster.local:3000"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_TIME_ZONE: "America/New_York"
  PAPERLESS_OCR_USER_ARGS: "{\"optimize\":1,\"pdfa_image_compression\":\"jpeg\"}"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_POLLING: "60"
