---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Paperless-Admin-User
        metadataPolicy: None
      secretKey: PAPERLESS_ADMIN_USER
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Paperless-Admin-Password
        metadataPolicy: None
      secretKey: PAPERLESS_ADMIN_PASS
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Paperless-Admin-Email
        metadataPolicy: None
      secretKey: PAPERLESS_ADMIN_MAIL
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Paperless-Secret-Key
        metadataPolicy: None
      secretKey: PAPERLESS_SECRET_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Postgres-Backup-Access-Key-Id
        metadataPolicy: None
      secretKey: backupAccessKeyId
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Postgres-Backup-Access-Secret
        metadataPolicy: None
      secretKey: backupAccessSecret
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: paperless-secrets
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        # Paperless App
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASS }}"
        PAPERLESS_ADMIN_MAIL: "{{ .PAPERLESS_ADMIN_MAIL }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        # CloudNativePG (DB Initialization)
        username: "paperless"
        password: "{{ .PAPERLESS_ADMIN_PASS }}"
        # CloudNativePG (Backups)
        backupAccessKeyId: "{{ .backupAccessKeyId }}"
        backupAccessSecret: "{{ .backupAccessSecret }}"
      engineVersion: v2
      mergePolicy: Replace
