apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: paperless
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: valkey
      app.kubernetes.io/controller: valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/instance: valkey
        app.kubernetes.io/controller: valkey
    spec:
      containers:
        - name: app
          image: ghcr.io/valkey-io/valkey:9.0.4
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: valkey
