---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  install:
    remediation:
      retries: -1
  interval: 1h
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    dns01RecursiveNameservers: 1.1.1.1:53,1.0.0.1:53
    dns01RecursiveNameserversOnly: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    replicaCount: 1
