---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-agent
  namespace: ai
spec:
  data:
    - remoteRef:
        key: Discord-Skippy-Bot-Token
      secretKey: discord_bot_token
    - remoteRef:
        key: CouchDB-User
      secretKey: couchdb_user
    - remoteRef:
        key: CouchDB-Password
      secretKey: couchdb_password
    - remoteRef:
        key: HASS-Skippy-Token
      secretKey: hass_token
    - remoteRef:
        key: Paperless-Api-Auth-Token
      secretKey: paperless_token
    - remoteRef:
        key: Github-Skippy-Token
      secretKey: github_token
    - remoteRef:
        key: Talos-Config
      secretKey: talos_config
    - remoteRef:
        key: Unifi-API-Key
      secretKey: unifi_api_key
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: hermes-agent-secret
    template:
      data:
        DISCORD_BOT_TOKEN: "{{ .discord_bot_token }}"
        COUCHDB_USER: "{{ .couchdb_user }}"
        COUCHDB_PASSWORD: "{{ .couchdb_password }}"
        HASS_URL: "http://home-assistant-app.automation.svc.cluster.local:8123"
        HASS_TOKEN: "{{ .hass_token }}"
        GH_TOKEN: "{{ .github_token }}"
        PPLS_HOSTNAME: "http://paperless.paperless.svc.cluster.local:8000"
        PPLS_TOKEN: "{{ .paperless_token }}"
        UNIFI_API_KEY: "{{ .unifi_api_key }}"
        TALOS_CONFIG: "{{ .talos_config }}"
      engineVersion: v2
