---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-agent
  namespace: ai
spec:
  data:
    - remoteRef:
        key: Discord-Skippy-Bot-Token
      secretKey: discord_bot_token
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: hermes-agent-secret
    template:
      data:
        DISCORD_BOT_TOKEN: "{{ .discord_bot_token }}"
      engineVersion: v2
