apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: home-ops
  sources:
    - repoURL: oci://ghcr.io/argoproj/argo-helm/argo-cd
      chart: argo-cd
      targetRevision: 9.4.17
      helm:
        valueFiles:
          - $values/kubernetes/apps/argocd/app/values.yaml
    - repoURL: https://github.com/binaryn3xus/HomeOps
      targetRevision: main
      ref: values
    - repoURL: https://github.com/binaryn3xus/HomeOps
      targetRevision: main
      path: kubernetes/argocd/core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
