# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - project-home-ops.yaml
  - argocd-install.yaml
  - argocd-httproute.yaml
  - platform-app.yaml
  - apps-app.yaml
