apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: home-ops
  source:
    repoURL: https://github.com/binaryn3xus/HomeOps
    targetRevision: main
    path: kubernetes/argocd/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
