---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: volsync-kopia-secret
spec:
  externalSecretName: volsync-kopia-secret

  namespaceSelectors:
    - matchLabels: {}

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: azure-keyvault
    target:
      template:
        engineVersion: v2
        data:
          KOPIA_FS_PATH: /repository
          KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
          KOPIA_REPOSITORY: filesystem:///repository
    data:
      - secretKey: KOPIA_PASSWORD
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: Kopia-Password
          metadataPolicy: None
