---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-backup-secrets
spec:
  data:
    - remoteRef:
        key: Palworld-Server-SSH-Private-Key
      secretKey: ssh_private_key
    - remoteRef:
        key: Palworld-Server-SSH-User
      secretKey: ssh_user
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: palworld-backup-secrets
    template:
      data:
        SSH_PRIVATE_KEY: "{{ .ssh_private_key }}"
        SSH_USER: "{{ .ssh_user }}"
      engineVersion: v2
