deploymentMode: SingleBinary
loki:
  auth_enabled: false
  analytics:
    reporting_enabled: false
  commonConfig:
    replication_factor: 1
  compactor:
    working_directory: /var/loki/compactor/retention
    delete_request_store: filesystem
    retention_enabled: true
  ingester:
    chunk_encoding: snappy
  limits_config:
    retention_period: 14d
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
  server:
    grpc_server_max_recv_msg_size: 10485760
    grpc_server_max_send_msg_size: 10485760
    log_level: info
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: ceph-block
    size: 50Gi
gateway:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
chunksCache:
  enabled: false
resultsCache:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
