apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: database
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudbeaver
      app.kubernetes.io/instance: cloudbeaver
      app.kubernetes.io/controller: cloudbeaver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudbeaver
        app.kubernetes.io/instance: cloudbeaver
        app.kubernetes.io/controller: cloudbeaver
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: app
          image: dbeaver/cloudbeaver:26.0.4@sha256:824c5e389155af3674b8e9a837bc4fd4454fcb43ac115c8be4c733e8b7315a4e
          env:
            - name: TZ
              value: America/New_York
          envFrom:
            - secretRef:
                name: cloudbeaver-secret
          ports:
            - name: http
              containerPort: 8978
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: workspace
              mountPath: /opt/cloudbeaver/workspace
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: cloudbeaver
