---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudbeaver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      cloudbeaver:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: dbeaver/cloudbeaver
              tag: "26.0.1@sha256:97df6d994d6f5b10a9e4708ad075302def39b9328d00b89f83040062d5e4f877"
            env:
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: cloudbeaver-secret
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: cloudbeaver
        ports:
          http:
            port: 8978

    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "true"
          gatus.home-operations.com/endpoint: |-
            conditions: ["len([BODY]) == 0"]
            group: internal
            dns:
              query-name: "{{ .Release.Name }}.unscfleet.com"
              query-type: A
            url: 1.1.1.1
        hostnames:
          - "{{ .Release.Name }}.unscfleet.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      workspace:
        enabled: true
        existingClaim: cloudbeaver
        globalMounts:
          - path: /opt/cloudbeaver/workspace
