---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudbeaver
  app.kubernetes.io/instance: cloudbeaver
  app.kubernetes.io/controller: cloudbeaver
resources:
  - ./pvc.yaml
  - ./replicationdestination.yaml
  - ./replicationsource.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./externalsecret.yaml
