---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: paperless
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.13
            env:
              TZ: "America/New_York"
              PAPERLESS_PORT: &port 8000
              PAPERLESS_URL: https://paperless.unscfleet.com
              PAPERLESS_REDIS: redis://valkey.paperless.svc.cluster.local:6379
              PAPERLESS_DBHOST: postgres-rw.paperless.svc.cluster.local
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBUSER: paperless
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secrets
                    key: PAPERLESS_ADMIN_PASSWORD
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_ENDPOINT: http://tika.paperless.svc.cluster.local:9998
              PAPERLESS_GOTENBERG_ENDPOINT: http://gotenberg.paperless.svc.cluster.local:3000
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_TIME_ZONE: "America/New_York"
              PAPERLESS_OCR_USER_ARGS: '{"optimize":1,"pdfa_image_compression":"jpeg"}'
            envFrom:
              - secretRef:
                  name: paperless-secrets
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 4000Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: paperless
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: synology
        globalMounts:
          - path: /usr/src/paperless/data
            subPath: data
      media:
        existingClaim: synology
        globalMounts:
          - path: /usr/src/paperless/media
            subPath: media
      export:
        existingClaim: synology
        globalMounts:
          - path: /usr/src/paperless/export
            subPath: export
      consume:
        existingClaim: synology
        globalMounts:
          - path: /usr/src/paperless/consume
            subPath: consume
