---
apiVersion: v1
kind: Endpoints
metadata:
  name: pikvm
  namespace: network
subsets:
  - addresses:
      - ip: 10.0.30.5
    ports:
      - name: http
        port: 80
      - name: https
        port: 443
