---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openclaw
  app.kubernetes.io/instance: openclaw
  app.kubernetes.io/controller: openclaw
resources:
  - ./pvc.yaml
  - ./configmap.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
