---
apiVersion: v1
kind: Service
metadata:
  name: openclaw
  namespace: ai
spec:
  ports:
    - name: http
      port: 18789
      targetPort: 18789
      protocol: TCP
  selector:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/instance: openclaw
    app.kubernetes.io/controller: openclaw
