---
# General Media PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-media
  namespace: automation
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: synology-nfs
  volumeName: synology-media-automation
  resources:
    requests:
      storage: 1Mi
