---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/persistentvolumeclaim_v1.json
# General Media PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-media
  namespace: automation
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: synology-nfs
  volumeName: synology-media-automation
  resources:
    requests:
      storage: 1Mi
