---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: SearXNG-Secret-Key
        metadataPolicy: None
      secretKey: searxng_secret_key
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: searxng-secret
    template:
      data:
        SEARXNG_SECRET: "{{ .searxng_secret_key }}"
      engineVersion: v2
      mergePolicy: Replace
