---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zwave
  namespace: default
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ZWave-Key-S0-Legacy
        metadataPolicy: None
      secretKey: KEY_S0_Legacy
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ZWave-Key-S2-Unauthenticated
        metadataPolicy: None
      secretKey: KEY_S2_Unauthenticated
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ZWave-Key-S2-Authenticated
        metadataPolicy: None
      secretKey: KEY_S2_Authenticated
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ZWave-Key-S2-AccessControl
        metadataPolicy: None
      secretKey: KEY_S2_AccessControl
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ZWave-Key-LR-S2-Authenticated
        metadataPolicy: None
      secretKey: KEY_LR_S2_Authenticated
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ZWave-Key-LR-S2-AccessControl
        metadataPolicy: None
      secretKey: KEY_LR_S2_AccessControl
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: zwave-secret
    template:
      data:
        KEY_S0_Legacy: "{{ .KEY_S0_Legacy }}"
        KEY_S2_Unauthenticated: "{{ .KEY_S2_Unauthenticated }}"
        KEY_S2_Authenticated: "{{ .KEY_S2_Authenticated }}"
        KEY_S2_AccessControl: "{{ .KEY_S2_AccessControl }}"
        KEY_LR_S2_Authenticated: "{{ .KEY_LR_S2_Authenticated }}"
        KEY_LR_S2_AccessControl: "{{ .KEY_LR_S2_AccessControl }}"
      engineVersion: v2
      mergePolicy: Replace
