---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worksphere
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/binaryn3xus/worksphere:1.0.17
          env:
            - name: EXPORT_PATH
              value: "/backups"
            - name: Export__OutputPath
              value: "/backups"
            - name: Export__ScheduledBackup__Enabled
              value: "true"
            - name: Export__ScheduledBackup__CronExpression
              value: "0 2 * * *"
            - name: Export__ScheduledBackup__MaxBackupHistory
              value: "60"
          envFrom:
            - secretRef:
                name: worksphere-secret
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: backup-storage
              mountPath: /backups
              subPath: Worksphere/backups
      volumes:
        - name: tmp
          emptyDir: {}
        - name: backup-storage
          persistentVolumeClaim:
            claimName: synology-kubernetes


