---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: worksphere
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: worksphere-secret
    template:
      engineVersion: v2
      data:
        ConnectionStrings__DefaultConnection: "{{ .db_connection }}"
  data:
    - remoteRef:
        key: WorkSphere-Database-Url
      secretKey: db_connection
