---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: worksphere
  app.kubernetes.io/instance: worksphere
  app.kubernetes.io/controller: worksphere
resources:
  - ./deployment.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./securitypolicy.yaml
  - ./service.yaml
