---
apiVersion: v1
kind: Service
metadata:
  name: worksphere
spec:
  selector:
    app.kubernetes.io/name: worksphere
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
