---
apiVersion: v1
kind: Service
metadata:
  name: worksphere
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: worksphere
    app.kubernetes.io/instance: worksphere
    app.kubernetes.io/controller: worksphere
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
