apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopia
  namespace: volsync-system
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kopia
      app.kubernetes.io/instance: kopia
      app.kubernetes.io/controller: kopia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kopia
        app.kubernetes.io/instance: kopia
        app.kubernetes.io/controller: kopia
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: app
          image: ghcr.io/home-operations/kopia:0.22.3@sha256:17ab64542280197a5368247deaefadc3e3bbe15714ab666c2455a06824e86efd
          args:
            - --without-password
          env:
            - name: TZ
              value: "America/New_York"
            - name: KOPIA_WEB_ENABLED
              value: "true"
            - name: KOPIA_WEB_PORT
              value: "80"
            - name: KOPIA_CONFIG_PATH
              value: "/config/repository.config"
            - name: KOPIA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kopia-secret
                  key: KOPIA_PASSWORD
          ports:
            - name: http
              containerPort: 80
          livenessProbe: &probe
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probe
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: config-file
              mountPath: /config/repository.config
              subPath: repository.config
              readOnly: true
            - name: repository
              mountPath: /repository
            - name: tmpfs
              mountPath: /config/cache
              subPath: cache
            - name: tmpfs
              mountPath: /config/logs
              subPath: logs
      volumes:
        - name: config-file
          configMap:
            name: kopia-repository-configmap
        - name: repository
          nfs:
            server: 10.0.30.4
            path: /volume1/Kubernetes/VolsyncKopia
        - name: tmpfs
          emptyDir: {}
