apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
spec:
  project: home-ops
  source:
    repoURL: https://github.com/binaryn3xus/HomeOps
    targetRevision: main
    path: kubernetes/apps/network/cloudflare-ddns
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
