---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Home-Wifi-2Gz-SSID
        metadataPolicy: None
      secretKey: home_wifi_ssid
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Home-Wifi-2Gz-Password
        metadataPolicy: None
      secretKey: home_wifi_password
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: esphome-secrets-file
    template:
      data:
        # Formatted specifically for ESPHome to find during build
        secrets.yaml: |
          wifi_ssid: "{{ .home_wifi_ssid }}"
          wifi_password: "{{ .home_wifi_password }}"
      engineVersion: v2
      mergePolicy: Replace
