---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: esphome-dst
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
