apiVersion: v1
kind: Service
metadata:
  name: unifi-dns
  namespace: network
spec:
  ports:
    - name: http
      port: 7979
      targetPort: 7979
      protocol: TCP
    - name: http-webhook
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/instance: unifi-dns
    app.kubernetes.io/name: external-dns
