apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: observability
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gatus
      app.kubernetes.io/instance: gatus
      app.kubernetes.io/controller: gatus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gatus
        app.kubernetes.io/instance: gatus
        app.kubernetes.io/controller: gatus
    spec:
      serviceAccountName: gatus
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: gatus-sidecar
          image: ghcr.io/home-operations/gatus-sidecar:0.0.13@sha256:40d549ea5ae89acac94bdf4cee1233e718a96c6e382c67f7e28de688511169d2
          args:
            - --auto-httproute
            - --enable-httproute
            - --enable-service
          env:
            - name: TZ
              value: America/New_York
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          restartPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: app
          image: ghcr.io/twin/gatus:v5.35.0@sha256:21609f31be8c4e680ce3004b24276305666239c99aff58391503f3fb6142f39d
          env:
            - name: GATUS_CONFIG_PATH
              value: /config
            - name: GATUS_WEB_PORT
              value: "80"
            - name: TZ
              value: America/New_York
          envFrom:
            - secretRef:
                name: gatus-secret
          ports:
            - name: http
              containerPort: 80
          livenessProbe: &probe
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probe
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - NET_RAW
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-file
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: config
              mountPath: /config
      volumes:
        - name: config-file
          configMap:
            name: gatus-configmap
        - name: config
          persistentVolumeClaim:
            claimName: gatus-config
