---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gatus
  namespace: &namespace observability
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/observability/gatus/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: status
      GATUS_WEB_PORT: "80"
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
