---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ai-secrets
  namespace: paperless
spec:
  data:
    - remoteRef:
        key: Paperless-AI-Token
      secretKey: PAPERLESS_API_TOKEN
    - remoteRef:
        key: Paperless-Admin-User
      secretKey: PAPERLESS_ADMIN_USER
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: paperless-ai-secrets
    template:
      metadata:
        labels:
          reloader.stakater.com/auto: "true"
      data:
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        PAPERLESS_USERNAME: "{{ .PAPERLESS_ADMIN_USER }}"
      engineVersion: v2
