---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ai
  namespace: paperless
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless-ai:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/clusterzx/paperless-ai
              tag: v3.0.9@sha256:2b65888163fd59716f1c8285b31c5bd0b30c9c3c192c42b516688e3887d4ba60
            env:
              TZ: "America/New_York"
              PUID: 1000
              PGID: 1000
              PAPERLESS_API_URL: http://paperless.paperless.svc.cluster.local:8000
              AI_PROVIDER: ollama
              OLLAMA_API_URL: http://ollama.ai.svc.cluster.local:11434
              OLLAMA_MODEL: llama3.2
              USE_RAG: "true"
              PORT: &port 3000
            envFrom:
              - secretRef:
                  name: paperless-ai-secrets
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 4000Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: paperless-ai
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
