---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Storage
  - ./synology-storage.yaml
  # Namespaces
  - ./ai
  - ./cert-manager
  - ./database
  - ./default
  - ./external-secrets
  - ./flux-system
  - ./games
  - ./kube-system
  - ./media
  - ./network
  - ./observability
  - ./openebs-system
  - ./paperless
  - ./rook-ceph
  - ./system-upgrade
  - ./teleport
  - ./volsync-system
