---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd/argocd/ks.yaml
  - ./cert-manager
  - ./flux-system
  - ./kube-system
  - ./network
  - ./openebs-system
  - ./rook-ceph
  - ./system-upgrade
  - ./teleport
  - ./volsync-system
