---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: unsc-gaming
  namespace: default
spec:
  endpoints:
    - dnsName: "satisfactory.unscfleet.com"
      recordType: A
      targets:
        - "100.91.15.5"
      providerSpecific:
        - name: cloudflare/proxied
          value: "false"
    - dnsName: "palworld.unscfleet.com"
      recordType: A
      targets:
        - "100.91.15.5"
      providerSpecific:
        - name: cloudflare/proxied
          value: "false"
    - dnsName: "minecraft.unscfleet.com"
      recordType: A
      targets:
        - "100.91.15.5"
      providerSpecific:
        - name: cloudflare/proxied
          value: "false"
