apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
      app.kubernetes.io/instance: unpoller
      app.kubernetes.io/controller: unpoller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unpoller
        app.kubernetes.io/instance: unpoller
        app.kubernetes.io/controller: unpoller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: app
          image: ghcr.io/unpoller/unpoller:v2.39.0@sha256:1cf63ad43121acc6995da1bd636063de9023b4bfc16599a4297951a6fb6b7fd2
          env:
            - name: TZ
              value: "America/New_York"
            - name: UP_POLLER_DEBUG
              value: "true"
            - name: UP_UNIFI_DEFAULT_URL
              value: https://10.0.30.1
            - name: UP_PROMETHEUS_HTTP_LISTEN
              value: 0.0.0.0:80
            - name: UP_INFLUXDB_DISABLE
              value: "true"
          envFrom:
            - secretRef:
                name: unpoller-secret
          ports:
            - name: http
              containerPort: 80
          livenessProbe: &probe
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe: *probe
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
