---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: black-box-discord
  namespace: ai
spec:
  data:
    - remoteRef:
        key: OpenClaw-Discord-Token
      secretKey: discord_token
    - remoteRef:
        key: OpenAI-API-Key
      secretKey: openai_api_key
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: black-box-discord-secret
    template:
      data:
        DISCORD_BOT_TOKEN: "{{ .discord_token }}"
        #OPENAI_API_KEY: "{{ .openai_api_key }}"
      engineVersion: v2
