---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: black-box
  app.kubernetes.io/instance: black-box
  app.kubernetes.io/controller: black-box
resources:
  - ./pvc.yaml
  - ./instance.yaml
  - ./httproute.yaml
  - ./externalsecret.yaml
