---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .sonarr_api_key }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .radarr_api_key }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .prowlarr_api_key }}"
        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .bazarr_api_key }}"
        HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .sabnzbd_api_key }}"
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: Sonarr-Api-Key
    - secretKey: radarr_api_key
      remoteRef:
        key: Radarr-Api-Key
    - secretKey: prowlarr_api_key
      remoteRef:
        key: Prowlarr-Api-Key
    - secretKey: bazarr_api_key
      remoteRef:
        key: Bazarr-Api-Key
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: Sabnzbd-Api-Key
