---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr
        property: api_key
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: prowlarr
        property: api_key
    - secretKey: BAZARR_API_KEY
      remoteRef:
        key: bazarr
        property: api_key
    - secretKey: SABNZBD_API_KEY
      remoteRef:
        key: sabnzbd
        property: api_key
