---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - externalsecret.yaml
  - rbac.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: homepage-config
    files:
      - config/settings.yaml
      - config/services.yaml
      - config/widgets.yaml
      - config/bookmarks.yaml
generatorOptions:
  disableNameSuffixHash: true
