---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: palworld-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SERVER_PASSWORD: "{{ .server_password }}"
        ADMIN_PASSWORD: "{{ .admin_password }}"
  data:
    - secretKey: server_password
      remoteRef:
        key: Palworld-Server-Password
    - secretKey: admin_password
      remoteRef:
        key: Palworld-Admin-Password

