---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minecraft-java
  namespace: &namespace games
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  interval: 30m
  # Minecraft Java server has been suspended for now. No need to run backups on it for now.
  patches:
    - patch: |
        apiVersion: volsync.backube/v1alpha1
        kind: ReplicationSource
        metadata:
          name: minecraft-java
        spec:
          paused: true
      target:
        kind: ReplicationSource
        name: minecraft-java
  path: ./kubernetes/apps/games/minecraft-java/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
