apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/controller: paperless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/instance: paperless
        app.kubernetes.io/controller: paperless
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: app
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.14
          envFrom:
            - configMapRef:
                name: paperless-config
            - secretRef:
                name: paperless-secrets
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
          securityContext:
            privileged: true
          volumeMounts:
            - name: synology
              mountPath: /usr/src/paperless/data
              subPath: data
            - name: synology
              mountPath: /usr/src/paperless/media
              subPath: media
            - name: synology
              mountPath: /usr/src/paperless/export
              subPath: export
            - name: synology
              mountPath: /usr/src/paperless/consume
              subPath: consume
      volumes:
        - name: synology
          persistentVolumeClaim:
            claimName: synology
