---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      version: v3.3.4
      sourceRef:
        kind: OCIRepository
        name: kyverno
        namespace: kyverno
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    admissionController:
      replicas: 2
    backgroundController:
      replicas: 2
    cleanupController:
      replicas: 2
    reportsController:
      replicas: 2
