---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    volsync.backube/privileged-movers: "true"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volsync.backube/privileged-movers: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-apps
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - list:
        elements:
          - app: mosquitto
            path: kubernetes/argo-apps/default/mosquitto
            wave: "-1"
          - app: audiobookshelf
            path: kubernetes/argo-apps/default/audiobookshelf
          - app: bazarr
            path: kubernetes/argo-apps/default/bazarr
          - app: esphome
            path: kubernetes/argo-apps/default/esphome
          - app: home-assistant
            path: kubernetes/argo-apps/default/home-assistant
          - app: it-tools
            path: kubernetes/argo-apps/default/it-tools
          - app: jellyfin
            path: kubernetes/argo-apps/default/jellyfin
          - app: maintainerr
            path: kubernetes/argo-apps/default/maintainerr
            wave: "1"
          - app: n8n
            path: kubernetes/argo-apps/default/n8n
          - app: overseerr
            path: kubernetes/argo-apps/default/overseerr
            wave: "1"
          - app: plex
            path: kubernetes/argo-apps/default/plex
          - app: prowlarr
            path: kubernetes/argo-apps/default/prowlarr
          - app: radarr
            path: kubernetes/argo-apps/default/radarr
            wave: "1"
          - app: sabnzbd
            path: kubernetes/argo-apps/default/sabnzbd
          - app: sonarr
            path: kubernetes/argo-apps/default/sonarr
            wave: "1"
          - app: tautulli
            path: kubernetes/argo-apps/default/tautulli
            wave: "1"
          - app: tdarr
            path: kubernetes/argo-apps/default/tdarr
          - app: vert
            path: kubernetes/argo-apps/default/vert
          - app: watchstate
            path: kubernetes/argo-apps/default/watchstate
            wave: "1"
          - app: zigbee
            path: kubernetes/argo-apps/default/zigbee
          - app: zwave
            path: kubernetes/argo-apps/default/zwave
  template:
    metadata:
      name: "{{.app}}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .wave | default "0" }}'
    spec:
      project: home-ops
      source:
        repoURL: https://github.com/binaryn3xus/HomeOps
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
