---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: teleport-dst
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes: ["ReadWriteOnce"]
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 5Gi
    cacheStorageClassName: openebs-hostpath
    capacity: 10Gi
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    repository: volsync-kopia-secret
    sourceIdentity:
      sourceName: teleport
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
