---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: gotenberg
  app.kubernetes.io/instance: gotenberg
  app.kubernetes.io/controller: gotenberg
resources:
  - ./deployment.yaml
  - ./service.yaml
