apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: gotenberg
    app.kubernetes.io/instance: gotenberg
    app.kubernetes.io/controller: gotenberg
