---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: Tailscale-HomeOps-Kubernetes-OAuth-Client-Id
    - secretKey: client_secret
      remoteRef:
        key: Tailscale-HomeOps-Kubernetes-OAuth-Key
