apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: network
data:
  config.yaml: |
    warp-routing:
      enabled: true
    ingress:
      - hostname: teleport.unscfleet.com
        service: https://teleport-cluster.teleport.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      - hostname: unscfleet.com
        originRequest:
          originServerName: unscfleet.com
        service: https://envoy-external.network.svc.cluster.local:443
      - hostname: "*.unscfleet.com"
        originRequest:
          originServerName: external.unscfleet.com
        service: https://envoy-external.network.svc.cluster.local:443
      - service: http_status:404
