---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificates/import/ks.yaml
  - ./certificates/export/ks.yaml
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./ddns-updater/ks.yaml
  - ./echo/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./pikvm/ks.yaml
  - ./unifi-dns/ks.yaml
